# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aabfea840cc5092ad9716ce10746fb31e5c2f7b649f0ae9c948050440085fdaa49942392c61842841074b1aa9fd52d82db7da096ebbd38f43b1713be194e3c93

test:
  secret_key_base: 298810306399d997f0c85400e6660010c184c45faa65c061073d55a53238a941be94844f6cd577e96cd915d8fae2620a377b43376a63ae9a2cca55c8bf780f01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
